### ISSUE TITLE
cMDTDriver in next release possible

### ISSUE THREAD

**Issue by FLeven** [pvs043/cMDTBuildLab#13]
A happy new one,

I will finally continue to move forward with DSC and MDT and managing drivers would be very handy
or is it possible to just use the DscResources from the original source ?

**Comment by pvs043** [comment]
@FLeven,
see #12 for understanding why you don't need drivers in cMDTBuildLab:
_"You don't need to duplicate any drivers. Most times you don't need any drivers at all in the ref-image, but if building in vmware you may want to, or if you are building a refimage for Windows To Go."_

Of course, you can use my code in your projects
