### ISSUE TITLE
cMDTBuildTaskSequenceCustomize - Support PowerShell scripts

### ISSUE THREAD

**Issue by FLeven** [pvs043/cMDTBuildLab#4]
To get the full logging support etc. when executing powershell scripts, one would have to add e new type to cMDTBuildTaskSequenceCustomize.psm1 by adding ZTIPowerShell.wsf right ?

**Comment by pvs043** [comment]
Yes! PowerShell is the best scripting language.
Maybe you can make an example for TS step in the Dev branch of my project?

**Comment by pvs043** [comment]
Working for Issue... @FLeven, Is that what you want to add?

MDT TS Step:
![ps](https://user-images.githubusercontent.com/15325412/38268256-14e7c9d6-3797-11e8-84a7-d03139f7761b.png)
ts.xml code:
`<step type="BDD_RunPowerShellAction" name="Run PowerShell Script" description="" disable="false" continueOnError="false" successCodeList="0 3010">

        <defaultVarList>
          <variable name="ScriptName" property="ScriptName">Test.ps1</variable>
          <variable name="Parameters" property="Parameters">param1</variable>
          <variable name="PackageID" property="PackageID"></variable>
        </defaultVarList>
        <action>cscript.exe "%SCRIPTROOT%\ZTIPowerShell.wsf</action>
      </step>
`

**Comment by FLeven** [comment]
Yes, thx.

**Comment by pvs043** [comment]
Done: #10
