### ISSUE TITLE
xSmbShare FolderDeploymentShare - Resolve SIDs to Friendly Names

### ISSUE THREAD

**Issue by FLeven** [pvs043/cMDTBuildLab#5]
You could translate the S-1-1-0 SID to the friendly name:

```
$objSID = New-Object System.Security.Principal.SecurityIdentifier("S-1-1-0") 
$objUser = $objSID.Translate( [System.Security.Principal.NTAccount]) 
```

and use `$objUser.Value` in **xSmbShare FolderDeploymentShare** to give **FullAccess** to **Everyone**.

This would work with every OS language, at the moment, non englisch OS versins will throw an error.

**Comment by pvs043** [comment]
@FLeven, I'm resolve this bug: Patch #161b95cf (dev)
