### ISSUE TITLE
cMDTBuildTaskSequenceCustomize - SetProductKey always returned as false

### ISSUE THREAD

**Issue by FLeven** [pvs043/cMDTBuildLab#6]
Starting your example configuration works without any error, but when testing your example with `Test-DscConfiguration`, the Resource **cMDTBuildTaskSequenceCustomize** - SetProductKey will always be returned as false and the configuration will always be reported as **InDesiredState = false**.

**Comment by pvs043** [comment]
@FLeven , thanks for your interest to my project cMDTBuildLab!
This #issue #6 is a Bug and I'm is working to resolve it. See devel Branch to receive patches.
p.s.: I'm a little busy at work - don't expect quick answers! :-)

**Comment by FLeven** [comment]
No worries, great project! I am working with MDT for years now and this DSC Module helps A lot.

**Comment by pvs043** [comment]
Fixed at Dev branch
