### ISSUE TITLE
Add Task Sequence Variable to a task possible ?

### ISSUE THREAD

**Issue by FLeven** [pvs043/cMDTBuildLab#7]
For example to execute a task only if a GUID matches or to execute a script only if the device is from a specific vendor ?

To be found in MDT -> Open a Task sequence -> highlight a task -> add -> Task Sequence Variable -> enter variable / condition / value

Not a big deal, because you could do the check in you scripts as well, but a lot of people use this to execute some of the tasks only under special circumstances (as some of the default tasks do: **Format and Partition Disk (UEFI)**)

**Comment by pvs043** [comment]
[cMDTBuildTaskSequenceCustomize](https://github.com/pvs043/cMDTBuildLab/wiki/cMDTBuildTaskSequenceCustomize):
* <b>[TSVarName]</b> - TS variable name
* <b>[TSVarValue]</b> - TS variable value
