### ISSUE TITLE
Remove APPX

### ISSUE THREAD

**Issue by FLeven** [pvs043/cMDTBuildLab#8]
Hi,

even still most of the people and users are missing this one: you need to add the **-alluser** parameter to remove appx for the current and future users.

`Get-AppxProvisionedPackage -Online | Remove-AppxProvisionedPackage -AllUsers`
and
`remove-AppxPackage -package $PackageFullName -AllUsers`

**Comment by pvs043** [comment]
Fixed: https://github.com/pvs043/cMDTBuildLab/commit/75710c47fddd1279eed959a724c9b3b14b6cf5b7
